version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./
      dockerfile: Dockerfile.gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AUTH_SERVICE=http://auth-service:5000
      - ADMIN_SERVICE=http://admin-service:5001
      - ANALYTICS_SERVICE=http://analytical-service:5002
      - REVIEW_SERVICE=http://review-service:5003
      - BID_SERVICE=http://bid-service:5004
      - PROJECT_SERVICE=http://project-service:5005
      - USER_SERVICE=http://user-service:5006
      - NOTIFICATION_SERVICE=http://notification-service:5007
      - SOCKET_SERVICE=http://socket-service:5008
    networks:
      - freelancer-network

networks:
  freelancer-network:
    external: true
